### ISSUE TITLE
Bug bei der Eingabe des Beginns und Ende eines Arbeitstag

### ISSUE THREAD

**Issue by ghost** [thomasbreitbach/studiplaner#2]
Wenn der Beginn um 18 uhr ist und das Ende um 02:29, kommt folgende Nachricht:
"Der Beginn deiner Arbeitszeit muss vor dem Ende liegen..." Die Eingabe ist aber valide, da man ja in der Theorie bis nachts Arbeiten kann..

**Comment by thomasbreitbach** [comment]
Wurde behoben. Arbeitszeiten sollten nun über 24/0 Uhr hinweg möglich sein.

Beginn: 23:00 Uhr
Ende: 03:00 Uhr 

Ergeben einen Workload von 4 Zeitstunden.
